// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "your@email.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/roasts": {
            "get": {
                "description": "Returns a random roast from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roasts"
                ],
                "summary": "Get a random roast",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved roast",
                        "schema": {
                            "$ref": "#/definitions/main.RoastResponse"
                        }
                    },
                    "404": {
                        "description": "No roasts found in database",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "No roasts found"
                }
            }
        },
        "main.RoastResponse": {
            "type": "object",
            "properties": {
                "roast": {
                    "type": "string",
                    "example": "Your code is so bad, even your comments are confused"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "roast-api.fly.dev",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Roast API",
	Description:      "A simple API that serves random roasts",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
